sudo: false
language: ruby
rvm: 2.3.3
script: ./deploy/cibuild
deploy:
    provider: pages
    skip-cleanup: true
    keep-history: true
    github-token: "o+0COW1WQfqHxeeCT+MSs0bG25tSwV0XG5T2LRkF7k6FwZ/ec3WxFOuSW4u3hHz6ZUysdBMokGDV8ZRszogZ7Vk/DMMj54vcFIwnWrcg4G5Btym47i0lywjJcSz2jQW2JlB9REcLwm/wODF7lPH4oYh+1N4CusPJ+RlnqUkeOT6GiBJBYMYOxDitx9EJBsbUD+VfThdynrZb2UPcu53uxQICq9PmkTeM1raWG19efMLV5e1+P4NhTUQlZ7ENTWEtA4xzvMxzzrw+ET0HXdhr7KLNSEFyI7QRO6kALA3oy5kPGu6WEd8MBzFBzKDoj1z75S89+FVR1233+L/h1tqZeAUP+61WIKb2jnBUFA4Akgl8EaUhn+B4JeJMI9/qI7KujpsWf5BWA7Kd5Ht050KJf47rYAa1daTfW8m/gt3ApVPrl+VzcKhPQ1hc6qJgnAD7M5C7X7CDBdgQal4J56rdVE6HoGtiWxOMcvj7Yyd0fZRGAlD0m6B9mU4EFAni2OYdVrb9SkbD/DBZiCLvjaLE+en6niEvpGpi194GeshJAID77cyH6VX9JtDoxM4pfLF5s8EBcuMbiaFLDyYyVfRvQMeYUcBTGBJs7finLKOUFls4nnIyK9VvmU3o0JgCeEZQIf1EndE2cy+lUulH1Vn5adWguif89rZpvHf4wI7+FM4="
    on:
        branch: master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
